apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: goweb-square-hpa
spec:
    maxReplicas: 6
    minReplicas: 1
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: goweb-square-hpa
    targetCPUUtilizationPercentage: 15